source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Ocha' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ocha
  pod 'Firebase'
  pod 'FirebaseAuth'
  pod 'FirebaseDatabase'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod ‘GoogleMaps’

end
